services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongodb:
    image: mongo 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=calyster123 
    ports:
      - 27017:27017
    volumes:
      - mongodata:/var/lib/mongodb/data/db
volumes:
  pgdata:
  mongodata:
